export const CALCULATION_METHODS = [
  { id: 0, name: "Shia Ithna-Ashari", flag: "🇮🇷" },
  { id: 1, name: "University of Islamic Sciences, Karachi", flag: "🇵🇰" },
  { id: 2, name: "Islamic Society of North America (ISNA)", flag: "🇺🇸" },
  { id: 3, name: "Muslim World League", flag: "🇸🇦" },
  { id: 4, name: "Umm Al-Qura University, Makkah", flag: "🇸🇦" },
  { id: 5, name: "Egyptian General Authority of Survey", flag: "🇪🇬" },
  { id: 7, name: "Institute of Geophysics, University of Tehran", flag: "🇮🇷" },
  { id: 8, name: "Gulf Region", flag: "🇦🇪" },
  { id: 9, name: "Kuwait", flag: "🇰🇼" },
  { id: 10, name: "Qatar", flag: "🇶🇦" },
  { id: 11, name: "Majlis Ugama Islam Singapura, Singapore", flag: "🇸🇬" },
  { id: 12, name: "Union Organization Islamique de France", flag: "🇫🇷" },
  { id: 13, name: "Diyanet İşleri Başkanlığı, Turkey", flag: "🇹🇷" },
  { id: 14, name: "Spiritual Administration of Muslims of Russia", flag: "🇷🇺" },
  { id: 15, name: "Moonsighting Committee Worldwide", flag: "🌍" },
  { id: 16, name: "Dubai", flag: "🇦🇪" },
  { id: 17, name: "Jabatan Kemajuan Islam Malaysia (JAKIM)", flag: "🇲🇾" },
  { id: 18, name: "Tunisia", flag: "🇹🇳" },
  { id: 19, name: "Algeria", flag: "🇩🇿" },
  { id: 20, name: "Kemenag Indonesia", flag: "🇮🇩" },
  { id: 21, name: "Morocco", flag: "🇲🇦" },
  { id: 22, name: "Portugal", flag: "🇵🇹" },
  { id: 23, name: "Jordan", flag: "🇯🇴" },
  { id: 24, name: "Ministry of Awqaf, Jordan", flag: "🇯🇴" },
  { id: 25, name: "Egypt (Custom)", flag: "🇪🇬" },
];
